### ISSUE TITLE
Brodart directions for Partners

### ISSUE THREAD

**Issue by kellymc03** [bywatersolutions/koha-plugin-edifact-enhanced#1]
Hi, 
In the directions for MarcItemFieldstoOrder-there are a few errors.  There needs to be only field per subfield value.  In the directions there are a few that are for two values such as $a, $p. Also there is two NotforLoan fields. Lastly the screenshot does not match the text above.

holdingbranch: 946$b
replacementprice: 946$v
notforloan: 946$7

Also, another step for Koha setup is turning on the EDI cron.

**Comment by kidclamp** [comment]
You should have access to edit the readme for the plugins if you have a
github account, or you can file issues on the plugin itself just to ensure
we don't miss following up here
